name: emn_plant
description: "EMN Plant workforce and job management app."
publish_to: none
version: 1.0.1+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  pocketbase: ^0.24.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: true
    image_path: assets/icon/icon.png
    icon_size: 48
